version: '3.8'

services:
  monerod:
    image: sethsimmons/simple-monerod:latest
    command: >
      monerod --stagenet
      --prune-blockchain
      --rpc-bind-ip=0.0.0.0
      --rpc-bind-port=38081
      --confirm-external-bind
      --disable-dns-checkpoints
    ports:
      - "38081:38081"
      - "38082:38082"
    volumes:
      - monero_data:/home/monero/.bitmonero
    networks:
      - wxmr_bridge

  relay:
    build: ./relay
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:///data/relay.db
      - MONERO_RPC_URL=http://monerod:38081/json_rpc
      - RUST_LOG=debug
    volumes:
      - relay_data:/data
    depends_on:
      - monerod
    networks:
      - wxmr_bridge

  fhe-engine:
    build: ./fhe-engine
    ports:
      - "8081:8081"
    environment:
      - FHE_SERVER_KEY_PATH=/keys/keys.server
    volumes:
      - fhe_keys:/keys
    networks:
      - wxmr_bridge

  testnet:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command: >
      --deterministic
      --accounts 10
      --host 0.0.0.0
      --port 8545
      --networkId 1337
      --chainId 1337
    networks:
      - wxmr_bridge

volumes:
  monero_data:
  relay_data:
  fhe_keys:

networks:
  wxmr_bridge:
    driver: bridge