[project]
name = "xmr-evm-bridge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "monero>=1.1.1",
    "mypy>=1.18.1",
    "requests>=2.32.5",
    "web3>=7.13.0",
]

[tool.mypy]
strict = true
